config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   #root "application#hello"
   root "pages#home"
   get '/about', to: 'pages#about'
   get '/help', to: 'pages#help'
   resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def hello
        render plain: "hello Sunayana!Welcome to your ToDO Lists App"
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
  end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :set_todo, only: [:edit, :update, :show, :destroy]
    
    def new
        @todo = Todo.new
    end

    def create
        @todo = Todo.new (todo_param)
        if @todo.save
            flash[:notice] = "todo has successfully created"
            redirect_to todo_path(@todo)
        else
            render 'new'
        end
    end

    def todo_param
        params.require(:todo).permit(:name,:description)
    end

    def show
       # @todo = Todo.find(params[:id])
    end

    def index
        @todos = Todo.all
    end

    def edit
       # @todo = Todo.find(params[:id])
    end

    def update
       # @todo = Todo.find(params[:id]) #gets the old values in that ID
        
        if @todo.update(todo_param)
            flash[:notice] = "todo has updated successfully"
            redirect_to todo_path(@todo)
        else
            render 'edit'
        end
    end

    def destroy
       # @todo = Todo.find(params[:id]) #gets the old values in that ID
        @todo.destroy
        flash[:notice] = "todo has deleted successfully"
        redirect_to todos_path    
    end

    def set_todo
        @todo = Todo.find(params[:id])
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flashmessages.html.erb
<% flash.each do |name,msg| %>
    <%= msg %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoAppRails7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <%= render "/layouts/flashmessages" %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About pages</h1>

app/views/pages/help.html.erb
<h1>pages help </h1>

app/views/pages/home.html.erb
<h1>Hello Kishore, Good Morning, I LOVE YOU SOOOOOOO MUCHHH</h1>
<h3>Nik telsa idi na first app. Diniki code antha nene rasi production server lo deploy chesa </h3>
<h4>Itlu Nee Sunayana with Love</h4>
<h6>Add /todos/new to the URL to create a new todo in your list</h6>
<h6>Add /todos to the URL to view your TODO list</h6>
<h6>Add /todos/[id]/edit to the URL to eit your particular TODO </h6>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
    <h3> Unsuccessful operation because of following errors:</h3>
    <ul>
        <% @todo.errors.full_messages.each do |msg| %>
            <li> <%= msg %> </li>
        <% end %>
    </ul>
<% end %>

<%= form_for @todo do |f|   %>
    <p>
        <%= f.label :name %> <br>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.label :description %> <br>
        <%= f.text_area :description %>
    </p>

    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/todos/edit.html.erb
<h3>Edit the todo : <%= @todo.id %> </h3>
<%= render "form" %> 

<%= link_to "Back To ToDos Listing", todos_path %>

app/views/todos/index.html.erb
<h1>List of your ToDos </h1>
<%= link_to "create a todo" , new_todo_path %> 

<table>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
    </tr>
    
    <% @todos.each do |todo| %>
        <tr>
            <td> <%= todo.id %> </td>
            <td> <%= todo.name %> </td> 
            <td> <%= todo.description %> </td>
            <td> <%= link_to "Edit" , edit_todo_path(todo) %> </td>
            <td> <%= link_to "Show" , todo_path(todo) %> </td>
            <td><%= button_to 'Delete', todo_path(todo), method: :delete, data: { confirm: "Are you sure?"} %></td>
            
            </tr>
    <% end %>
</table>   

app/views/todos/new.html.erb
<h1>Create a new Todo</h1>
<%= render "form" %> 
<td><%= link_to "Back To List", todos_path %></td>

app/views/todos/show.html.erb
<h3>showing todo: <%= @todo.id %> </h3>
    <p>
        name : <%= @todo.name %>
    </p>

    <p>
        description : <%= @todo.description %>
    </p>
    <%= link_to "Edit this todo", edit_todo_path(@todo) %> |
    <%= link_to "Back to todos listing", todos_path %>

app/views/todos/update.html.erb
<h3>todo ID :<%= @todo.id %> updated successfully </h3>
<h3>showing todo : <%= @todo.id %> </h3>
    <p>
        name : <%= @todo.name %>
    </p>
    <p>
        description : <%= @todo.description %>
    </p>